#!/usr/bin/env python3
"""Issue a new root-signed ATPP key list from tools/atpp/atpp-keys.json.

The root key signs nothing else, so it can live offline (password manager / hardware key) and come out
only for a rotation or revocation:

  1. edit tools/atpp/atpp-keys.json — add a scan key with not_before/not_after, or list a keyid in "revoked"
  2. python3 tools/atpp/keylist.py --root /path/to/atpp-root-ed25519.pem
  3. also update workers/atf-badge/src/keys.js (tests fail until every copy agrees), commit, and put the
     root key back offline.

Writes tools/atpp/atpp-keylist.dsse.json, trust/.well-known/atpp-keylist.dsse.json and the embedded copy
inside atpp.py, with the serial bumped by one (verifiers refuse a lower serial than they embed).
"""
import argparse, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import atpp  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True, help="the offline root private key (PEM)")
    ap.add_argument("--issued", help="YYYY-MM-DD (default today, UTC)")
    a = ap.parse_args()
    key = atpp.load_private_key(a.root)
    rid = next(iter(atpp.ROOT_KEYS))
    src = json.load(open(os.path.join(HERE, "atpp-keys.json")))
    from datetime import datetime, timezone
    doc = {"_type": "https://millenniums.ai/atpp/keylist/v1", "root": rid,
           "serial": atpp.KEYLIST_SERIAL + 1,
           "issued": a.issued or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
           "keys": {k: {"public_key": v["public_key"], "not_before": v["not_before"], "not_after": v["not_after"],
                        "use": v.get("use", "scan")} for k, v in src["keys"].items()},
           "revoked": sorted(src.get("revoked") or [])}
    env = atpp.sign(atpp.KEYLIST_TYPE, doc, key, rid)
    atpp.keylist_from(env)                                   # refuses unless the pinned root verifies it
    text = json.dumps(env, indent=1) + "\n"
    for p in (os.path.join(HERE, "atpp-keylist.dsse.json"), os.path.join(ROOT_DIR, "trust", ".well-known", "atpp-keylist.dsse.json")):
        open(p, "w").write(text)
    src_py = open(os.path.join(HERE, "atpp.py")).read()
    block = ("# >>> embedded keylist (generated by tools/atpp/keylist.py — do not edit by hand)\n"
             f"EMBEDDED_KEYLIST = {json.dumps(env)}\n# <<< embedded keylist")
    src_py, n = re.subn(r"# >>> embedded keylist.*?# <<< embedded keylist", lambda m: block, src_py, flags=re.S)
    assert n == 1, "embedded keylist markers not found in atpp.py"
    open(os.path.join(HERE, "atpp.py"), "w").write(src_py)
    print(f"key list serial {doc['serial']} signed by {rid}: {sorted(doc['keys'])}, revoked {doc['revoked']}")


if __name__ == "__main__":
    main()
